---
version: '3'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  wordpress:
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      WP_ENVIRONMENT_TYPE: 'local'
    depends_on:
      - db
      - mailhog
    build: ./docker/wordpress
    ports:
      - 3090:80
    restart: always
    volumes:
      - wordpress:/var/www/html
      - .htaccess:/var/www/html/.htaccess
      - .:/var/www/html/wp-content/themes/siteblock
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - .mu-plugins:/var/www/html/wp-content/mu-plugins
      - .fonts:/var/www/html/wp-content/fonts
      - .vendor:/var/www/html/vendor
    working_dir: /var/www/html
  wp:
    image: wordpress:cli
    working_dir: /var/www/html
    user: '33:33'
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/siteblock
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - .mu-plugins:/var/www/html/wp-content/mu-plugins
      - .fonts:/var/www/html/wp-content/fonts
      - .vendor:/var/www/html/vendor
    links:
      - db
    command: "--info"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
    restart: always
    ports:
      - 3091:80
    volumes:
      - /sessions
  composer:
    image: composer
    command: install
    working_dir: /var/www/html
    depends_on:
      - wordpress
    volumes:
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - wordpress:/var/www/html
      - .uploads:/var/www/html/wp-content/uploads
      - .plugins:/var/www/html/wp-content/plugins
      - .mu-plugins:/var/www/html/wp-content/mu-plugins
      - .fonts:/var/www/html/wp-content/fonts
      - .vendor:/var/www/html/vendor
    links:
      - wordpress:wordpress
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 3094:1025 # smtp server
      - 3095:8025 # web ui
volumes:
  db_data:
  wordpress:
